[[constraint]]
  name = "github.com/karlseguin/ccache"
  version = "2.0.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.1.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"
